### PR TITLE
Optimize Select#selected_options and Select#value using JS

### PR DESCRIPTION
**Pull request by abotalov**
Continuation from #540

### CODE REVIEW

**Comment by titusfortner** [comment]
If we don't call `#options` we still need to add a line for `#wait_for_exists` to make sure select list is there before working with it.

**Comment by abotalov** [comment]
Done.

**Comment by p0deje** [comment]
There is always a chance element goes stale during script execution, so this should probably be wrapped with `element_call(:wait_for_exists)`.

**Comment by titusfortner** [comment]
merged: 1f22570e0cb46e66ca9296f5837fb78792d99e20

**Pull request closed without merging**
