### PR TITLE
have `#wait_while_present` always relocate

### PR DESCRIPTION
**Pull request by titusfortner**
@p0deje - you ok with this feature?

### CODE REVIEW

**Comment by p0deje** [comment]
Why we need that?

**Comment by titusfortner** [comment]
https://github.com/watir/watir/pull/479#issuecomment-259735670

**Comment by titusfortner** [comment]
Another option... 

```
def not_present?
  self.reset!
  !present?
end

element.wait_until(&:not_present?)
```

Is there actually any other scenario in which `wait_while` makes sense for an element?
Bret commented before that he didn't see a compelling reason for a separate `wait_while` method, and thought that it made more sense to just have `wait_until` with people passing in their true conditionals even if that meant using `!=` instead of `==`, etc.

If we implement a `not_present?` maybe we can also get rid of `wait_while` as well?

**Comment by azohra** [comment]
@titusfortner in terms of elegance, having an ability to avoid `!` is always nice - especially as it allows us to take advantage of `&:` notation. 

While `not_present` sounds like a good alternative (which preserves `&:` notation), I see a slippery slope where folks may want/expect negative decorators for all the popular methods (`not_exist`,`not_visible`,`not_enabled`).

``` ruby
loading_modal.wait_while(&:present?)
vs
loading_modal.wait_until {|e| !e.present?}
```

the former is just so wonderful to read. /my 2 cents

**Review by p0deje — DISMISSED** [review]
Can we add a spec for this behavior so that we don't have regression if we try to refactor?

**Comment by titusfortner** [comment]
@p0deje - added the spec... kind of unfortunate that it only applies to `#wait_while_present` instead of `#wait_while(&:present?)`... but it would break implementations if people use: `element.wait_while(&:stale?)`

**Review by p0deje — APPROVED** [review]

**Comment by titusfortner** [comment]
Merged - 21fe9325913dfe1e3a4f81f2ea63fa6b78886398

**Pull request closed without merging**
