### PR TITLE
Implements Capybara's advanced Regexp Matching for XPath generation

### PR DESCRIPTION
**Pull request by titusfortner**
This restores the functionality Watir had in 6.14 that was removed in previous PRs. The previous implementation handled some of the wild cards incorrectly. This does a more thorough job of parsing partial matches for adding into the XPath

### CODE REVIEW

**Review by p0deje — APPROVED** [review]
My eyes are bleeding, but as long as it works, I approve.

**Comment by titusfortner** [comment]
Right? I'm mostly treating that class like a black box. :)

**Comment by titusfortner** [comment]
Ok, Capybara changed implementations. the `regexp_parser` gem does everything the previous implementation did, plus better support for escaped characters.

**Comment by Rajagopalan-M** [comment]
This is something amazing, we get knowledge from people from cabypara since
it is also sit on the top of Ruby Selenium Binding.

**Comment by titusfortner** [comment]
@Rajagopalan-M well, Capybara was stealing stuff from Watir and then made it much better in the process, so Watir is just stealing it back now. (seriously, though, we've been discussing ways to approach these common challenges, and I agree it is a very good thing).

**Comment by Rajagopalan-M** [comment]
Ah! Okay!

**Review by jkotests — APPROVED** [review]

**Comment by titusfortner** [comment]
whoops, didn't squash this.

**Pull request merged**
