### PR TITLE
updating deprecated Selenium Error classes

### PR DESCRIPTION
**Pull request by joesho112358**

### CODE REVIEW

**Comment by kapoorlakshya** [comment]
Hi @joesho112358, would you mind fixing this one as well?

```
2019-04-22 13:28:06 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::NoAlertPresentError is deprecated. Use Selenium::WebDriver::Error::NoSuchAlertError (e
nsure the driver supports W3C WebDriver specification) instead.
```

**Comment by joesho112358** [comment]
> Hi @joesho112358, would you mind fixing this one as well?

Hey, looks to me like that is a Selenium issue that'll be fixed in the next big selenium release.

**Comment by kapoorlakshya** [comment]
@joesho112358 Oh, okay. Do you have a link to an Issue/commit were you learned that this will be fixed in Selenium v4? Looks like it was deprecated in `3.141.5926` based on [6f6af6e](https://github.com/SeleniumHQ/selenium/commit/6f6af6e8e5d4dbebac45b9d185ee4326d0cb8072#diff-1828458d7e816f8e53b81cf1952df377R350).

**Comment by joesho112358** [comment]
Should be here https://github.com/SeleniumHQ/selenium/commit/3eefcd600c4c7cf71dd9dd9c0d770ac4546ac834#diff-1828458d7e816f8e53b81cf1952df377

Within this branch https://github.com/SeleniumHQ/selenium/compare/rb-selenium-4

**Comment by kapoorlakshya** [comment]
@joesho112358 Thanks for the links! I can't find any instances of `NoAlertPresentError` in the `master` branch of `watir` so I think we're good.

**Comment by titusfortner** [comment]
yeah, the NoAlertErrors are coming from Chrome itself. I'll be back to working on Watir things shortly, sorry for the delays.

**Comment by jkotests** [comment]
@joesho112358 , sorry for taking so long to get to this. It looks like the `Selenium::WebDriver::Error::InvalidElementStateError` is actually sticking around:
* Still in Selenium v4: https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/error.rb
* Still defined in the WebDriver spec: https://www.w3.org/TR/webdriver/#errors

If you want to re-add that error, I can then get this merged in.

**Comment by joesho112358** [comment]
@jkotests should be added back in

**Comment by jkotests** [comment]
Thanks @joesho112358

**Pull request merged**
