### PR TITLE
Handle passing in IE Options

### LINKED ISSUE #768: No way to pass IE Options
## Meta -
Watir Version: `6.12.0

Currently, any `options` passed for IE get deleted and ignored in `Capabilities`. There is a way to get them in via `desired_capabilities`, but that's marked as deprecated.

Selenium Ruby bindings do offer an IEOptions class now as well.

### PR DESCRIPTION
**Pull request by lmtierney**
This fixes #768

### CODE REVIEW

**Comment by lmtierney** [comment]
Rubocop complains of `Watir::Capabilities` being too long. Not sure if we want to ignore it or try and get it smaller. It's a beast

**Comment by titusfortner** [comment]
I've been hiding from capabilities class. Anyone want to meet up in person in November and hack on this and selenium things maybe with me? @Justin want to go to Des Moines for a weekend with me? :)

**Comment by lmtierney** [comment]
> want to go to Des Moines for a weekend

said nobody ever

**Comment by jkotests** [comment]
12 hour drive to talk about capabilities... I think I'll have to pass. To be honest, I don't know much about capabilities.

**Comment by titusfortner** [comment]
@jkotests yeah, none of us do really, which is part of the issue. :)
@lmtierney so it's settled we all need to go to Toronto. @joshmgrant wants to join as well.

**Pull request merged**
