### PR TITLE
BugFix for the issue #813. execute_script does not wait for element

### PR DESCRIPTION
**Pull request by reach2jeyan**
@titusfortner This is my first PR. Can you please provide your comments?

### CODE REVIEW

**Comment by titusfortner** [comment]
Ok, the first step is to add a test that fails under current code and passes with new code.
The second step is to run the existing specs to make sure that they pass with the new code. In this case, `#wait_for_exists` calls `#assert_exist`, so you're going to get a Stack Level error: https://travis-ci.org/watir/watir/jobs/453874195

There are two places that call `#execute_script` and the idea is to wait for any elements that are passed in; so like inside the block here: https://github.com/watir/watir/blob/master/lib/watir/browser.rb#L216

**Comment by titusfortner** [comment]
@reach2jeyan are you still interested in working on this? What help do you need?

**Comment by reach2jeyan** [comment]
@titusfortner Can you let me know if we can jump into a quick slack call?

**Comment by titusfortner** [comment]
@reach2jeyan what is your timezone again? Message me on slack and we'll figure something out.

**Comment by titusfortner** [comment]
So... #813 fix was too simple to walk through the PR for it. Essentially specs already exist for the functionality we needed to use. We'll walk through a different issue tomorrow. Fortunately(?) there are 29 more open issues we can go through to find something to work on.

**Pull request closed without merging**
