### PR TITLE
fix the big bug I made in #exist? and #present?

### LINKED ISSUE #852: When checking for staleness deprecation warning is raised by checking for the presence of a stale element, the element will always be declared not present.
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: 71.0.3578.98
Browser Driver Version: 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90)
OS Version: Windows 10.0.16299 Build 16299

## Expected Behavior -
I have an element on the page that becomes stale due to other elements being added and removed from the dom causing it to move itself, I expect that when i ask if it was present, It should be found without me having to manually relocate it.  (If you want an example, i'll need time to build one in fiddle or something)
## Actual Behavior -
The element is stated as not found unless we recheck it.

Looking through how the deprecation is raised, i was able to figure out *why* this happens.
```ruby
    def present?
      displayed = display_check
      if displayed.nil? && display_check
        Watir.logger.deprecate 'Checking `#present? == false` to determine a stale element',
                               '`#stale? == true`',
                               reference: 'http://watir.com/staleness-changes',
                               ids: [:stale_present]
      end
      displayed
    rescue UnknownObjectException, UnknownFrameException
      false
    end
```

In this block the display check in `if displayed.nil? && display_check` is not presisted back to displayed, so it returns the first result, even after relocating after the reset!.

Defining
```ruby
    def present?
      displayed = display_check
      if displayed.nil? && (displayed = display_check)
        Watir.logger.deprecate 'Checking `#present? == false` to determine a stale element',
                               '`#stale? == true`',
                               reference: 'http://watir.com/staleness-changes',
                               ids: [:stale_present]
      end
      displayed
    rescue UnknownObjectException, UnknownFrameException
      false
    end
```
seems to fix it.

### LINKED ISSUE #853: Browser#execute_script does not wait for stale argument elements to exist
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: Chrome 72.0.3626.96
Browser Driver Version: Chromedriver 2.46
OS Version: Windows 10

## Expected Behavior -

`Browser#execute_script` waits for all elements in the arguments Array to exist.

## Actual Behavior -

`Browser#execute_script` times out if any of the elements are stale.

## Steps to reproduce -

Given a page with a select list:

~~~~~~~~
<html>
  <body>
    <select id="ctl00_ctl00_BC_MC_MainTS_AA_ViewOptions">
        <option>A</option>
        <option>B</option>
    </select>
  </body>
</html>
~~~~~~~~

Getting the text of a stale select list will time out:

~~~~~~~~
select = browser.select_list
select.exists?
browser.refresh
select.text
#=> C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/wait.rb:46:in `until': timed out after 30 seconds, waiting for true condition on #<Watir::Select: located: true; {:tag_name=>"select"}> (Watir::Wait::TimeoutError)
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/wait.rb:125:in `wait_until'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/browser.rb:218:in `block in execute_script'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/browser.rb:217:in `map!'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/browser.rb:217:in `execute_script'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/js_snippets.rb:13:in `execute_js'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/select.rb:139:in `block in selected_options'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/element.rb:789:in `element_call'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/select.rb:139:in `selected_options'
#=> 	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.16.5/lib/watir/elements/select.rb:129:in `text'
~~~~~~~~

### PR DESCRIPTION
**Pull request by titusfortner**
Full explanation for why is here: https://github.com/watir/watir/issues/852#issuecomment-462615080

The solution is very simple at least.

fixes #852
fixes #853

### CODE REVIEW

**Comment by kapoorlakshya** [comment]
Thanks for fixing this! Looking forward to the next release.

**Review by jkotests — APPROVED** [review]
Looks good to me, behaviour is back to what is was:
<pre>
version         exists?         visible?         present?
 6.8.3          true            true             true
6.10.3          true            true             true
6.13.0          false           exception        false
6.16.5          false           exception        nil   
bug fix         true            true             true
</pre>

**Comment by Castone22** [comment]
Thanks for the hard work!

**Comment by Castone22** [comment]
@titusfortner Any updates on this?

**Comment by titusfortner** [comment]
Yeah, there are like 5 PRs I need to merge in, and I haven't had a chance to sit down with everything. Hopefully this weekend.

**Comment by PanoramicPanda** [comment]
Any update on this getting into a release? :)

**Comment by titusfortner** [comment]
Yeah, it's been a busy past month. I'm fixing up webdrivers gem right now, then need to make sure watir is working with the latest selenium before I can do a release. Thanks for your patience.

**Pull request closed without merging**
