### PR TITLE
id should still be validated with the tag name

### PR DESCRIPTION
**Pull request by titusfortner**
This is for issue #442 

I'm not sure why we've allowed id to match any tag name. It seems like if it is specified it should be required to match.

### CODE REVIEW

**Comment by p0deje** [comment]
👍

**Comment by titusfortner** [comment]
Oh, wow, this actually causes tests to fail. For realsies.
`non_control_elements.html` has 4 different tags with `id="lead"`
I'm not sure how we want to deal with this.
1. If the first matching id value doesn't match the tag, fail it
2. Assume that you may need to test a website with more than one of the same id on it and treat it like any other multiple selector

**Comment by titusfortner** [comment]
Regardless, the wrong elements were getting matched in our specs. :)

**Comment by titusfortner** [comment]
Ok, so it turns our that in `#by_id` we deleted :tag_name to verify no extra parameters, but didn't put it back in when sending it to the element_validation class. This should fix it.

**Comment by titusfortner** [comment]
This also is needed for this PR - https://github.com/watir/watirspec/pull/92

**Comment by p0deje** [comment]
I think it was based on the assumption that IDs are unique, so we don't care about anything else (tag_name).

**Comment by titusfortner** [comment]
merged - 99b5d467de5022d6985a6a494b408fa561da0f2c

**Pull request closed without merging**
