### PR TITLE
Update for Ruby 2.4.0

### PR DESCRIPTION
**Pull request by titusfortner**
Require Selenium 3.0.5

### CODE REVIEW

**Comment by titusfortner** [comment]
Huh, I swear I tested it on < 2.4 before the PR. I'll fix it.

**Comment by p0deje** [comment]
There is still quite a log of Fixnum:

```
$ git grep Fixnum
lib/watir/after_hooks.rb:    # @return [Fixnum]
lib/watir/after_hooks.rb:    # @param [Fixnum] index
lib/watir/browser.rb:    # @param [Fixnum] timeout
lib/watir/element_collection.rb:    # @return [Fixnum]
lib/watir/element_collection.rb:    # @param [Fixnum] idx Index of wanted element, 0-indexed
lib/watir/generator/base/visitor.rb:          Fixnum
lib/watir/legacy_wait.rb:    # @param [Fixnum] timeout seconds to wait before timing out
lib/watir/legacy_wait.rb:    # @param [Fixnum] timeout seconds to wait before timing out
lib/watir/wait.rb:      # @param [Fixnum] timeout How long to wait in seconds
lib/watir/wait.rb:      # @param [Fixnum] timeout How long to wait in seconds
lib/watir/wait.rb:    # @param [Fixnum] timeout seconds to wait before timing out
lib/watir/wait.rb:    # @param [Fixnum] timeout seconds to wait before timing out
lib/watir/wait.rb:    # @param [Fixnum] timeout seconds to wait before timing out
lib/watir/wait.rb:    # @param [Fixnum] timeout seconds to wait before timing out
lib/watir/wait/timer.rb:      # @param [Fixnum] timeout
lib/watir/window.rb:    # @param [Fixnum] width
lib/watir/window.rb:    # @param [Fixnum] height
lib/watir/window.rb:    # @param [Fixnum] x
lib/watir/window.rb:    # @param [Fixnum] y
spec/element_locator_spec.rb:      it "raises a TypeError if :index is not a Fixnum" do
```

**Review by p0deje — CHANGES_REQUESTED** [review]
1. Let's get rid of all Fixnum usage.
2. Can we squash commits?

**Comment by MacCracken** [comment]
Thanks for getting on this guys....

**Comment by titusfortner** [comment]
@MacCracken - this PR includes your PR. You can see the results of your PR here:
https://travis-ci.org/watir/watir/builds/187041459 - If you want to update your PR (add in the latest version in .travis.yml, set the gemspec to use selenium 3.0.5 gem and then start fixing other warnings), feel free. Let me know, though, because I'm probably going to take another stab at this tonight.

@p0deje - I'm also going to take this opportunity to suppress expected warnings in all of our specs, since I think I found a way to do that.

**Comment by MacCracken** [comment]
That why I revised my comment... I realized after looking at the changes.  I will take a pass at repairing some warnings.

**Comment by titusfortner** [comment]
merged into master

**Comment by vitorgalvao** [comment]
@titusfortner Will there be a specific release for this fix?

**Comment by titusfortner** [comment]
Yes: http://watir.github.io/watir-6-1/

**Pull request closed without merging**
